export const mockDataQuestions = [
    {
        id: 0,
        question: "What is not on this screen?",
        answers: [
            "A useful question",
            "Birds",
            "The beautiful ocean",
            "A fishing net",
        ],
        correctAnswer: 0,
        difficulty: 0,
    },
    {
        id: 1,
        question: "What is the answer to this question? (hint: answer 1)",
        answers: [
            "Answer 1",
            "Answer 2",
            "Answer 3",
            "Answer 4",
        ],
        correctAnswer: 0,
        difficulty: 0,
    },
    {
        id: 3,
        question: "What is the color of the sun?",
        answers: [
            "green",
            "blue",
            "yellow",
            "black",
        ],
        correctAnswer: 2,
        difficulty: 0,
    },
    {
        id: 5,
        question: "How cool is this quiz?",
        answers: [
            "Cool",
            "Cooler",
            "Very cool",
            "The coolest",
        ],
        correctAnswer: 3,
        difficulty: 0,
    },
    {
        id: 8,
        question: "Who wrote War and Peace?",
        answers: [
            "Oscar Wilde",
            "Leo Tolstoy",
            "Victor Hugo",
            "William Shakespeare",
        ],
        correctAnswer: 1,
        difficulty: 2,
    },
    {
        id: 10,
        question: "...?",
        answers: [
            "Correct!",
            "...",
            "...",
            "...",
        ],
        correctAnswer: 0,
        difficulty: 1,
    },
    {
        id: 15,
        question: "Is this the last question?",
        answers: [
            "No",
            "No",
            "Yes",
            "No",
        ],
        correctAnswer: 2,
        difficulty: 1,
    },
    {
        id: 16,
        question: "This is another question",
        answers: [
            "yes",
            "falsch",
            "falsch",
            "falsch",
        ],
        correctAnswer: 1,
        difficulty: 1,
    },
    {
        id: 17,
        question: "Frage",
        answers: [
            "click me",
            "falsch",
            "falsch",
            "falsch",
        ],
        correctAnswer: 1,
        difficulty: 1,
    },
    {
        id: 18,
        question: "Frage",
        answers: [
            "RICHTIG",
            "falsch",
            "falsch",
            "falsch",
        ],
        correctAnswer: 1,
        difficulty: 1,
    },
    {
        id: 19,
        question: "Frage",
        answers: [
            "RICHTIG",
            "falsch",
            "falsch",
            "falsch",
        ],
        correctAnswer: 1,
        difficulty: 1,
    },
    {
        id: 20,
        question: "Frage",
        answers: [
            "RICHTIG",
            "falsch",
            "falsch",
            "falsch",
        ],
        correctAnswer: 1,
        difficulty: 1,
    }
];